[package]
name = "alarm_clock"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
reqwest = "0.12.8"
chrono = "0.4.38"
# tokio = "1.40.0"
tokio = {version = "1.40.0", features = ["full"]}

